---
functional:
  - Пользователи должны иметь возможность соревноваться друг с другом
  - Пользователи должны видеть, как их соперники пишут код в режиме реального времени
  - Должна быть система, отслеживающая рейтинги игроков
  - Должна быть предусмотрена возможность игры против бота
  - Должна быть возможность приглашать друзей для игры по ссылке
non-functional:
  - Сайт должен быть интуитивно понятным
  - Сайт должен быть оптимизирован для быстрой загрузки и работы
  - Сайт должен быть безопасным и защищать данные пользователей
  - Сайт должен быть удобным для использования на мобильных устройствах
  - Сайт должен корректно работать в последних версиях современных браузеров
  - Система должна выдерживать большое количество одновременных пользователей
implicit:
  - Предполагается, что у проекта будет пользовательский интерфейс, с которым пользователи могут взаимодействовать
  - Пользователи должны иметь возможность зарегистрироваться и войти в систему для доступа к функциям
  - Система должна быть доступна круглосуточно
  - Система должна соответствовать основным стандартам веб-разработки
